```{r}
#options(repos = list(CRAN = "http://cran.rstudio.com/"))
#install.packages("sf")
#install.packages("stars")
#install.packages("tmap")

```
```{r}
# Load packages
library(tidyverse)
library(sf)
library(here)
library(tmap)
```


```{r}
# Read in geodatabase of EJScreen data at the Census Block Group level
ejscreen <- sf::st_read(here::here("data", "ejscreen","EJSCREEN_2023_BG_StatePct_with_AS_CNMI_GU_VI.gdb"))
```


```{r}
# Select a smaller area to work with
california <- ejscreen |>
  filter(ST_ABBREV=="CA") 
```
```{r}
slo <- ejscreen |>
  filter(CNTY_NAME %in% c("San Luis Obispo County")) 
```
```{r}
# Map percentiles of PM 2.5 in SLO county 
tm_shape(slo) + 
  tm_polygons(fill = "P_PM25", fill.legend = tm_legend(title = "PM 2.5 Percentile",))+
  tm_title("PM2.5 Concentrations in San Luis Obispo County", size=1) +
  tm_graticules(labels.size=.45) 
```

```{r}
# Map percentiles of cancer in SLO county 
tm_shape(slo)+ 
  tm_polygons(fill = "P_CANCER", fill.legend = tm_legend(title = "Cancer Percentile",)) +
  tm_title("Cancer in San Luis Obispo County", size=1)+
  tm_graticules(labels.size=.45) 
```
